services:
  - type: web
    name: banner-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 300
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CLOUDINARY_CLOUD_NAME
        value: divlmyzig
      - key: CLOUDINARY_API_KEY
        value: 573712429865238
      - key: CLOUDINARY_API_SECRET
        value: m_yHXjNUHkm8N2S05Jt3mkgig5w
